from sqlalchemy import Column, Integer, Float, String, Table, MetaData

CUSTOMER_BEHAVIOUR_COLUMNS = [
    ("age", Integer),
    ("monthly_income", Integer),
    ("daily_internet_hours", Float),
    ("smartphone_usage_years", Integer),
    ("social_media_hours", Float),
    ("online_payment_trust_score", Integer),
    ("tech_savvy_score", Integer),
    ("monthly_online_orders", Integer),
    ("monthly_store_visits", Integer),
    ("avg_online_spend", Integer),
    ("avg_store_spend", Integer),
    ("discount_sensitivity", Integer),
    ("return_frequency", Integer),
    ("avg_delivery_days", Integer),
    ("delivery_fee_sensitivity", Integer),
    ("free_return_importance", Integer),
    ("product_availability_online", Integer),
    ("impulse_buying_score", Integer),
    ("need_touch_feel_score", Integer),
    ("brand_loyalty_score", Integer),
    ("environmental_awareness", Integer),
    ("time_pressure_level", Float),
    ("gender", String),
    ("city_tier", String),
    ("shopping_preference", String),
]
